### ISSUE TITLE
Enhance netbox_inventory.py to support Netbox >= 2.7

### ISSUE THREAD

**Issue by jeremyschulman** [jeremyschulman/netcfgbu#33]
The current netbox_inventory.py script is written for the Netbox API < 2.7.  Need to enhance the script to support >= 2.7 API changes.

**Comment by jeremyschulman** [comment]
Also need to address the behavior of `limit=0` per @mtbutler07 thread on Twitter here: https://twitter.com/mtbutler07/status/1270537702652420107

**Comment by jeremyschulman** [comment]
@mtbutler07 - when I ran a test using Netbox 2.8 and set limit=0 I received all devices (>1000).
I am not observing the MAX_PAGE_SIZE (1000) pagination that you noted in your tweet.  Could you please elaborate on the behavior you were expecting?

**Comment by mtbutler07** [comment]
Hey Jeremy,

I just tested this out again, I have several thousands of devices on this particular instance.

The count value always returns the total count of devices.

```bash
$ curl -s -H "Authorization: Token $NETBOX_API_KEY" https://$NETBOX_URL/api/dcim/devices/?limit=0 | jq '.count'
7868
```

But doesn't _actually_ return all of the results if the limit is 0 or exceeds the MAX_PAGE_SIZE

Using curl and jq I can get the actual length of the results

```bash
$ curl -s -H "Authorization: Token $NETBOX_API_KEY" https://$NETBOX_URL/api/dcim/devices/?limit=0 | jq '.results | length'
1000
```

**Comment by mtbutler07** [comment]
I've spent part of today working on a way to retrieve the full device inventory using asyncio and httpx. Trying to do this synchronously is far too time consuming. I've had some success using the small snippet below.

1. Set a reasonable batch size
2. Get the count of total devices in Netbox
3. Use the range function to format the URLs and add the limit and offset parameters
`for offset in range(0, total_count, batch)`
4. Use HTTPx to make asynchronous API calls and gather the results.
5. Unpack the results as normal

Still needs some work
```python
import asyncio
from os import environ

import httpx

netbox_base_url = environ.get("NETBOX_URL")
token = environ.get("NETBOX_TOKEN")
batch = 500
headers = {"Authorization": f"Token {token}", "Accept": "application/json"}


async def get_netbox_devices(client, batch, offset):
    params = {
        "limit": batch,
        "offset": offset,
        "status": "active",
        "exclude": "config_context",
        "has_primary_ip": True,
    }

    return await client.get(url="/api/dcim/devices/", params=params)

async def main():
    async with httpx.AsyncClient(
        timeout=90, verify=True, headers=headers, base_url=netbox_base_url
    ) as client:

        count_resp = await client.get("/api/dcim/devices/?limit=1")
        total_count = count_resp.json()["count"]

        combined_resp = await asyncio.gather(
            *[
                get_netbox_devices(client, batch, offset)
                for offset in range(0, total_count, batch)
            ]
        )

        devices = [res.json()["results"] for res in combined_resp][0]


if __name__ == "__main__":
    asyncio.run(main())

```

```python

```
