### ISSUE TITLE
Change config section [[github]] to [[git]] 

### ISSUE THREAD

**Issue by jeremyschulman** [jeremyschulman/netcfgbu#48]
The `netcfgbu` tool can be used with any git based system, which includes GitLab for example.  This issue tracks the **BREAKING CHANGE** to the configuration file to rename the section name from "github" to simply "git".

See discussion in #47 for further details.

cc @minitriga

**Comment by minitriga** [comment]
I have a branch that this is implemented in if you would like me to push it?

**Comment by jeremyschulman** [comment]
@minitriga - awesome, thank you!  I've merged to develop!
